version: '2'
services:
  zk:
    image: jplock/zookeeper:3.4.6
    ports:
     - 2181:2181

  master:
    image: mesosphere/mesos-master:0.28.0-2.0.16.ubuntu1404
    network_mode: host
    environment:
      MESOS_ZK: zk://192.168.99.100:2181/mesos
      MESOS_HOSTNAME: 192.168.99.100
      MESOS_IP: 192.168.99.100
      MESOS_QUORUM: 1
      MESOS_CLUSTER: for_marathon_dev
      MESOS_WORK_DIR: /var/lib/mesos
    depends_on:
      - zk

  slave:
    image: mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://192.168.99.100:2181/mesos
      MESOS_HOSTNAME: 192.168.99.100
      MESOS_IP: 192.168.99.100
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - master

  slave2:
    image: mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://192.168.99.100:2181/mesos
      MESOS_HOSTNAME: 192.168.99.100
      MESOS_IP: 192.168.99.100
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5052
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - master

  slave3:
    image: mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://192.168.99.100:2181/mesos
      MESOS_HOSTNAME: 192.168.99.100
      MESOS_IP: 192.168.99.100
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5053
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - master

  marathon:
    image: mesosphere/marathon:v1.1.1
    network_mode: host
    environment:
      MARATHON_MASTER: zk://192.168.99.100:2181/mesos
      MARATHON_ZK: zk://192.168.99.100:2181/marathon
      MARATHON_HOSTNAME: 192.168.99.100
      MARATHON_EVENT_SUBSCRIBER: http_callback
      MARATHON_MESOS_ROLE: marathon
      MARATHON_MESOS_AUTHENTICATION_PRINCIPAL: marathon
    depends_on:
      - zk
      - master

  chronos:
    image: mesosphere/chronos:chronos-2.4.0-0.1.20150828104228.ubuntu1404-mesos-0.27.0-0.2.190.ubuntu1404
    ports:
      - "8081:8080"
    links:
      - "zk:zk"
    command: "/usr/bin/chronos --master zk://zk:2181/mesos --zk_hosts zk://zk:2181/mesos"
    depends_on:
      - zk
      - master
