version: '2'
services:
  
  zk:
    image: zookeeper:3.4.9
    network_mode: host

  master:
    image: mesosphere/mesos-master:1.0.3
    network_mode: host
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
    volumes:
      - ./log/mesos:/var/log/mesos
      - ./tmp/mesos:/var/tmp/mesos
    depends_on:
      - zk

  slave:
    image: mesosphere/mesos-slave:1.0.3
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
    volumes:
      - ./log/mesos:/var/log/mesos
      - ./tmp/mesos:/var/tmp/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
      - /usr/bin/docker:/usr/bin/docker
    depends_on:
      - master

  # marathon:
  #   image: mesosphere/marathon:v1.4.1
  #   network_mode: host
  #   environment:
  #     MARATHON_MASTER: zk://127.0.0.1:2181/mesos
  #     MARATHON_ZK: zk://127.0.0.1:2181/marathon
  #     MARATHON_ENABLE_FEATURES: task_killing
  #   depends_on:
  #     - zk
  #     - master

  # chronos:
  #   image: mesosphere/chronos:v3.0.2
  #   ports:
  #     - "8081:8080"
  #   links:
  #     - "zk:zk"
  #   command: "/usr/bin/chronos --master zk://zk:2181/mesos --zk_hosts zk://zk:2181/mesos"
  #   depends_on:
  #     - zk
  #     - master
